=head1 CREDITS

Credit for this script belongs to the following persons:

Idea   - Matt Simerson  matt at tnpi.biz

Funding -

 Justin Bennett   justin at z-axis.com       1
 Fred Gildred     fgildred at downeast.com   1
 Rick Romero      rick at valeoinc.com       1
 Adam Seniuk      adams at techweavers.net   1
 David Chaplin-Loebell david at klatha.com   1
 Randy Ricker     randy at 3dwebworks.com    1
 Chris Odell  chris at redstarnetworks.net
 Marius Kirschner marius at agoron.com
 Philip Jocks     philip at jocks.to         1
 Khari Atiba      akana.com           (m/o)  1
 Joe Kletch       joe at cedar.net           1
 Joe Kletch       joe at cedar.net           1
 Joe Kletch       joe at cedar.net           1
 Rich Shappart    knitebane @ knitebane.net  1
 Arie Gerszt      arie at gerszt.ch          1
 Dan Daggett      dan at socialgeeks.com     1
 Lee Imber        lee at mac.com             1

Coding - Matt Simerson

=cut
