
#
# $Id: FAQ-CGI.pod,v 4.0 2004/11/16 20:57:31 matt Exp $
#

=head1 Where can I see it?

http://mail.cadillac.net/


=head1 Can I edit it?

The file has an index.tmpl file that comes with it. It's a (almost) pure HTML page that you can edit to please your tastes. If you do a good job of editing it, drop me a note.


=head1 Where do I get it?

index.cgi is part of the Mail::Toaster package. You can get it from here: 
http://www.tnpi.biz/computing/mail/toaster/Mail-Toaster.tar.gz

=head1 Can I use it without the rest of your toaster?

Yes, you will need still need to install Mail::Toaster and HTML::Parser but once that's done, Mail::Toaster::CGI will work for you. 

=head1 What needs to be done to Apache for use?

You need to enable the .cgi handler, add index.cgi to the DirectoryIndex, and enable ExecCGI on the directory index.cgi is installed in. See the contrib directory of the Mail::Toaster distribution for a diff (for perusal) and a patch file (to be applied against an Apache2 httpd.conf). Here is the diff:

  391c392
      Options Indexes FollowSymLinks
  ---
      Options Indexes FollowSymLinks ExecCGI
  439c440
  DirectoryIndex index.html index.html.var
  ---
  DirectoryIndex index.cgi index.html index.html.var
  908c911,913
  #AddHandler cgi-script .cgi
  ---
  AddHandler cgi-script .cgi

Reload Apache and you're all set.

=cut
