#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Toaster
version:      3.33
version_from: lib/Mail/Toaster.pm
installdirs:  site
requires:
    Date::Parse:                   1
    DBI:                           1
    Net::DNS:                      0.2
    MATT::FreeBSD:                 1
    MATT::Utility:                 1.2
    MATT::Perl:                    1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
