# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Toaster
version:      5.01
version_from: lib/Mail/Toaster.pm
installdirs:  site
requires:
    Date::Parse:                   1
    DBI:                           1
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
