---
name: Mail-Toaster
version: 5.05
author:
  - "Matt Simerson (matt@tnpi.net)"
abstract: turns a computer into a secure, full-featured, high-performance mail server.
license: bsd
requires:
  Date::Parse: 2.0
  Digest::HMAC_MD5: 1
  Digest::MD5: 2
  Digest::SHA1: 2
  Net::DNS: 0.5
  Net::IP: 1.25
  Params::Validate: 0.8
build_requires:
  Test::More: 0
no_index:
  directory:
    - contrib
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Mail::Toaster:
    file: lib/Mail/Toaster.pm
    version: 5.05
  Mail::Toaster::Apache:
    file: lib/Mail/Toaster/Apache.pm
    version: 5.05
  Mail::Toaster::CGI:
    file: lib/Mail/Toaster/CGI.pm
    version: 5.01
  Mail::Toaster::DNS:
    file: lib/Mail/Toaster/DNS.pm
    version: 5.01
  Mail::Toaster::Darwin:
    file: lib/Mail/Toaster/Darwin.pm
    version: 5.04
  Mail::Toaster::Ezmlm:
    file: lib/Mail/Toaster/Ezmlm.pm
    version: 5.02
  Mail::Toaster::FreeBSD:
    file: lib/Mail/Toaster/FreeBSD.pm
    version: 5.05
  Mail::Toaster::Logs:
    file: lib/Mail/Toaster/Logs.pm
    version: 5.05
  Mail::Toaster::Mysql:
    file: lib/Mail/Toaster/Mysql.pm
    version: 5.05
  Mail::Toaster::Passwd:
    file: lib/Mail/Toaster/Passwd.pm
    version: 5.05
  Mail::Toaster::Perl:
    file: lib/Mail/Toaster/Perl.pm
    version: 5.05
  Mail::Toaster::Provision:
    file: lib/Mail/Toaster/Provision.pm
    version: 5.05
  Mail::Toaster::Qmail:
    file: lib/Mail/Toaster/Qmail.pm
    version: 5.05
  Mail::Toaster::Setup:
    file: lib/Mail/Toaster/Setup.pm
    version: 5.05
  Mail::Toaster::Utility:
    file: lib/Mail/Toaster/Utility.pm
    version: 5.05
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
