#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Toaster
version:      4.00
version_from: lib/Mail/Toaster.pm
installdirs:  site
requires:
    DBI:                           1
    Net::DNS:                      0.2
    Date::Parse:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
